Add twitter to footer #14
OperationCodeKC/opcodekc.org pull request #17
Opened 2023-09-23 15:41 UTC by IanWorley

2023-09-23 15:42 UTC, JustinKSU requested changes

2023-09-23 15:42 UTC, JustinKSU commented on index.html
> +    />
Fix line breaks

2023-09-24 02:53 UTC, IanWorley commented
Hey @JustinKSU I am ready for another code review ask me if you want me to make any other changes?

2023-09-24 12:17 UTC, JustinKSU approved these changes

2023-09-24 12:17 UTC, merged